### ISSUE TITLE
Repositories::Updater#recreate spec is flakey

### ISSUE THREAD

**Issue by sgerrand** [FundingCircle/shipment_tracker#215]
🙎  The `Repositories::Updater#recreate` spec does not run predictably. An example of a recent failure follows:
```
Failures:

  1) Repositories::Updater#recreate resets and forces a run
     Failure/Error: expect(Snapshots::EventCount.find_by_id(last_updated_event.id)).to be_blank
       expected `#<Snapshots::EventCount id: 2, snapshot_name: "global_event_pointer", event_id: 3>.blank?` to return true, got false
     # ./spec/models/repositories/updater_spec.rb:134:in `block (3 levels) in <top (required)>'
```

**Comment by sgerrand** [comment]
Happened again.
```
Failures:

  1) Repositories::Updater#recreate resets and forces a run
     Failure/Error: expect(Snapshots::EventCount.find_by_id(last_updated_event.id)).to be_blank
       expected `#<Snapshots::EventCount id: 2, snapshot_name: "global_event_pointer", event_id: 2>.blank?` to return true, got false
     # ./spec/models/repositories/updater_spec.rb:134:in `block (3 levels) in <top (required)>'

Finished in 17.54 seconds (files took 7.05 seconds to load)
686 examples, 1 failure

Failed examples:

rspec ./spec/models/repositories/updater_spec.rb:120 # Repositories::Updater#recreate resets and forces a run
```
https://circleci.com/gh/FundingCircle/shipment_tracker/2365
